kind: Service
apiVersion: v1
metadata:
  name: proj-2-service
  namespace: proj-2
spec:
  selector:
    app: proj-2
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8000
  # type: LoadBalancer
